---
kind: Service
apiVersion: v1
metadata:
  name: quiz-svc
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
---
kind: Endpoints
apiVersion: v1
metadata:
  name: quiz-svc
subsets:
  - addresses:
        - ip: 54.162.128.250
        - ip: 54.157.58.70
        - ip: 52.204.242.176
        - ip: 18.205.36.100
    ports:
      - port: 80
        name: web