---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-prod-{{ .Values.appVersion | default .Chart.AppVersion }}"
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv