---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "db-{{ .Values.appVersion | default .Chart.AppVersion | replace "." "-" }}"
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: postgres:13-alpine
          name: db
          env:
            - name: POSTGRES_DB
              value: news
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: PGDATA
              value: /data/pgdata
          volumeMounts:
            - name: "postgres-db-{{ .Values.appVersion | default .Chart.AppVersion | replace "." "-" }}"
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: "postgres-db-{{ .Values.appVersion | default .Chart.AppVersion | replace "." "-" }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
