version: '2.1'

networks:
  db_net:
    driver: bridge

volumes:
    postgres_db: {}
    postgres_backup: {}

services:

  postgres:
    image: postgres:12
    container_name: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - postgres_backup:/var/lib/postgresql/backup
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - db_net
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - db_net
    ports:
      - 8080:8080
