Vagrant.configure("2") do |config|
    config.vm.network "public_network",
        use_dhcp_assigned_default_route: true
    config.vm.define :vm1 do |vm1|
        vm1.vm.box = "bento/ubuntu-20.04"
        vm1.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 1
        vm1.vm.network "forwarded_port", guest: 19999, host: 19999
        vm1.vm.network "forwarded_port", guest: 9100, host: 9100
        vm1.vm.network "forwarded_port", guest: 443, host: 443
        vm1.vm.network "forwarded_port", guest: 80, host: 80
        end
    end
    config.vm.define :vm2 do |vm2|
        vm2.vm.box = "bento/ubuntu-20.04"
        vm2.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 1
        end
    end
end