---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fron-back
  name: fron-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fron-back
  template:
    metadata:
      labels:
        app: fron-back
    spec:
      containers:
        - image: danilabar/13-kubernetes-config_frontend:latest
          name: frontend
          ports:
            - containerPort: 80
          env:
            - name: BASE_URL
              value: http://localhost:9000
        - image: danilabar/13-kubernetes-config_backend:latest
          name: backend
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres.stage.svc.cluster.local:5432/news
          ports:
            - containerPort: 9000
      restartPolicy: Always