apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: multitool
      image: praqma/network-multitool:alpine-extra
      volumeMounts:
        - mountPath: "/static"
          name: my-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: pvc
